name: Event-demo
on:
  workflow_dispatch:
  
    
jobs:
  event-check:
  runs-on: sirpi
  steps:
    - name: Output of all the events
      run: "${{ toJSON(github) }}"
    - name: Checkout to repository
      run: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: test
      run: npm run test
    - name: build the code
      run: npm run build
    - name: deploy the code
      run: echo "deploying the code"
