name: Event Demo
on:
  pull_request:
    types:
      - opened
    branches:
      - master
      - "dev-**"
      - "feat**"
  workflow_dispatch:
  push:
    branches:
     - master
     - "dev-**"
     - "feat**"
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output event data
        run: "${{ toJSON(github) }}"
      - name: checkout to repo
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: test dependency
        run: npm test
      - name: build the code
        run: npm run build
      - name: deploy the code
        run: echo "deploying code"
