name: Event Demo1
on:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output event of the data
        run: "${{ toJSON(github) }}
      - name: get code
        run: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: test the code
        run: npm test
      - name: build
        run: npm run build
      - name: Deploy the code
        run: echo "Deploy the code"
