name: Deploy
on:
  push:
    branches:
      - master
      
jobs:
  Test:
    runs-on: sirpi
    steps:
      - uses: actions/checkout@v3
        
      - name: install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint
        
      - name: testing code
        run: npm run test
