name: Deploy
on:
  push:
    branches:
      - master
      
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: install dependencies
        run: npm ci
        
      - name: testing code
        run: npm run test
  Build:
    needs: Test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - uses: actions/checkout@v3
      
      - name: install dependencies
        run: npm ci
        
      - name: building code
        run: npm run build
        
      - name: Pulish JS names
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
   
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: dist-files
          path: dist
            #dist
            #package.json
        
        
  deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: output content
        run: ls
      - name: output filename
        run: echo "${{ needs.build.outputs }}"
      - name: deploy
        run: echo "deploying"
    
    
